### ISSUE TITLE
Time Box Five

### ISSUE THREAD

**Issue by livstanley29** [signofthehorns/watson-ta#43]
# TODO

- [x] Add button on website to link to messenger bot @Varcho 
- [x] Testing @dltn 
- [x] Entity RR Search @livstanley29  #42 
- [x] Clean Up @3ygun #44 
- [x] Render what type of questions @3ygun #39 
- [x] Questions editing @3ygun #39 
- [x] Export final pdf @3ygun #49 
- [x] Improve parsing / ranking #38, #7, finalized in #56  
- [x] Fix multiple choice @3ygun #38, #52 
- [x] Biology data @tylermzeller #7, #53, finalized in #56 
- [x] Drag partial answers @Varcho @dltn
- [x] Poster @livstanley29

# To Skip

- [ ] ~~Save user pdf uploads and answers to server #28~~

**Comment by Varcho** [comment]
![Alt Text](https://m.popkey.co/21f8aa/ZpgAl.gif)

**Comment by 3ygun** [comment]
Closing as all major Timebox 5 features are complete! 🎉 🌮 🎉
